name: Secrets and Environment Variables

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_API_KEY: ${{ vars.NEXT_PUBLIC_AIRTABLE_BASE_ID }}

    steps:
      - name: Read a variable
        run: echo "My NEXT_PUBLIC_AIRTABLE_API_KEY value is ${{ vars.NEXT_PUBLIC_AIRTABLE_BASE_ID }}"

      - name: Tell me a secret!
        run: echo "My existing secret is ${{ secrets.API_KEY }}"
      
      - name: Unset secret
        run: echo "My unknown secret is ${{ secrets.DOES_NOT_EXIST }}"
      
      - name: Github stuff
        run: echo "My Github repo is called ${{ github.repository }}"
      
      - name: Read an env variable
        run: echo "My APP_ID value is ${{ env.NEXT_PUBLIC_AIRTABLE_BASE_ID }} (also accessible as $AIRTABLE_API_KEY)"

      - uses: actions/checkout@v2
      - name: Read the env from an external script
        run: |
         chmod +x .github/scripts/custom.sh
         .github/scripts/custom.sh
        shell: bash
  
  top-secret-production:
    runs-on: ubuntu-latest
    environment: production
    env:
      NEXT_PUBLIC_AIRTABLE_BASE_ID: ${{ vars.NEXT_PUBLIC_AIRTABLE_BASE_ID }}

    steps:
      - name: Read a variable
        run: echo "My APP_ID value in the production job is $NEXT_PUBLIC_AIRTABLE_BASE_ID"